chore: add pre-push git hooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -45,8 +45,12 @@ EOF
 	exit 1
 fi
 
-make lint
-make test
+if ! make test >/dev/null 2>&1; then
+	echo "test failed"
+	exit 1
+else
+	echo "test passed"
+fi
 
 # If there are whitespace errors, print the offending file names and fail.
 exec git diff-index --check --cached $against --
